# Cassandra configuration for odp common errors
spring:
  data:
    cassandra:
      port: 9042
      contact-points: 127.0.0.1
      keyspace-name: book_store
      schema-action: create_if_not_exists
      user-name: cassandra
      password: cassandra
      entity-base-package: com.demo.spring.boot.cassandra.docker.repository

